# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  labels: 
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
