apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: postgres
spec:
 serviceName: "postgres"
 replicas: 1
 selector:
    matchLabels:
      app: postgres
 template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: nfs-pvc
          mountPath: /var/lib/postgresql/data
 volumeClaimTemplates:
 - metadata:
    name: nfs-pvc
   spec:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 5Gi
    storageClassName: nfs
 # volumeClaimTemplates:
 # - metadata:
 #      name: nfs-pvc
 #   spec:
 #      accessModes: ["ReadWriteOnce"]
 #      resources:
 #        requests:
 #          storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
 name: postgres-secret
type: Opaque
stringData:
 password: dGVzdAo=
---
