include: 
  - template: Security/SAST.gitlab-ci.yml
  - project: "templates/ci"
    file: "DockerInDockerTemplate.yml"

stages:
   - docker-build
   - test
   - analysis
 
docker-build-frontend:
  stage: docker-build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - docker build --tag $CI_REGISTRY_IMAGE/momo-frontend:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE/momo-frontend:$CI_COMMIT_SHA

spotbugs-sast:
  dependencies:
    - docker-build-frontend
  artifacts:
    paths:
      - gl-sast-report.json
  rules:
    - changes:
        - frontend/**/*
  variables:
    COMPILE: "false"

sonarqube:
  stage: analysis
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner -Dsonar.qualitygate.wait=false
      -Dsonar.projectKey=12_Pavel_Kozlov_front
      -Dsonar.projectName=12_Pavel_Kozlov_front
      -Dsonar.host.url=${Sonar_url}
      -Dsonar.login=${Sonar_token_front}
