# этот докер компилирует proto файл + делает rest api
version: "3.3"
services:
  protoc-all:
    image: namely/protoc-all:latest
    user: "1000:1000"
    command: 
      -d proto
      -o gen/pb-go
      -i third_party/googleapis
      -l go
      --with-gateway
    volumes:
      - ./:/defs
