# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    endpoint                    = "storage.yandexcloud.net"
    bucket                      = "demo-terragrunt-states-backend"
    region                      = "ru-central1-a"
    key                         = "folder/terraform.tfstate"
    access_key                  = "YCAJEra89P0L_uqAqjmb6nbA-"
    secret_key                  = "YCMrjgWENY03TmgpEYiIsdtJnV363X7yogjcJxeh"

    skip_region_validation      = true
    skip_credentials_validation = true
  }
}
