---
apiVersion: v1
kind: Service
metadata:
  name: frontnp
  labels:
    app: frontnp
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30036
  selector:
    app: frontend
